# Generated by Django 5.1.5 on 2025-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
