# Generated by Django 5.1.5 on 2025-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partner_slug_alter_partner_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='partners/images/'),
        ),
        migrations.AddField(
            model_name='partner',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='partners/videos/'),
        ),
    ]
